# PythonNumpyHands-On

# Why do we need Numpy ? when have list?

List from Python

In [ ]:
#list
height=[1.73,1.68,1.71]

weight=[65.4,59.2,88.1]

print(height)
print(weight)


#type(height)

bmi=weight/height*2
#print(bmi)

# Create Numpy Array

In [ ]:
import numpy as np


#creating a list
lheight=[1.73,1.68,1.71,12]

lweight=[65.4,59.2,88.1,13]

#creating a numpy array
np_height= np.array(lheight)



#print(np_height)
np_weight= np.array(lweight)

print(np_height)

print(np_weight)

bmi=np_weight/np_height**2

print('bmi',bmi)

#np_height*2

type(np_height)




# 1-Dimensional Array

In [ ]:
#import numpy as np
#import numpy to make use of it in the program
a = np.array([1,2,3,4,5,6,7,8])
print(a)
print(type(a))
#dimensions
print(a.ndim)
#shape-rows and columns (R,C)
print(a.shape)

# 2-Dimensional Array

In [ ]:
#import numpy as np
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(b.ndim)
print(b.shape)

#(rows,columns)

In [ ]:
#import numpy as np
#b = np.array([[1,2,3],[4,5,6],[7,8,9],[4,5,6],[4,5,6]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.ndim)
print(b.shape)

#(rows,columns)

# 3-Dimensional Array

1)shape(2, 2, 3)
(Depth/layers,Row,Col)

In [ ]:
b = np.array([[[1,2,3],[3 ,4,3]],[[5,6,3],[7, 8,3]]])
print(b)
print(b.ndim)
print(b.shape)


2)shape(2, 2, 3)
(Depth/layers,Row,Col,)

In [ ]:
b = np.array([[[1,2,],[3 ,4]],[[5,6],[7, 8]],[[5,6],[7, 8]],[[5,6],[7, 8]],[[5,6],[7, 8]]])
print(b)
print(b.ndim)
print(b.shape)


2)shape(2, 2, 2)
(Depth/layers,Row,Col)

In [ ]:
arr1d= np.arange(8)
print(arr1d)
print('******arr3d******')
arr3d = np.arange(8).reshape(2, 2, 2)
print(arr3d)
print(arr3d.ndim)
print(arr3d.shape)

In [ ]:
arr3da = np.arange(24).reshape(4, 3, 2)
print(arr3da)
print(arr3da.ndim)
print(arr3da.shape)

2)shape(3, 4, 3)
(Depth/layers,Row,Col)

In [ ]:

arr = np.arange(36).reshape(3, 4, 3)

arr



# 4-D dimensions

In [ ]:
import numpy as np
b = np.array([[[[1,2,3],[4,5,6],[7,8,9],[1,2,3],[1,2,3]]]])

print(b)
print(b.ndim)
print(b.shape)

#(rows,columns,layers)

In [ ]:
#dir(np)

# Intialize Numpy Array - 1 D array and 2 Array

# Initialize all the elements of x X y array to 0

In [ ]:
#import numpy as np
np.zeros((5,5))

#np.
#lweight.

In [ ]:
#set a datype as integer
np.zeros((3,4),dtype = int)
#eek.zeros(2, dtype = int) 

intialize it to 1

In [ ]:
np.ones((3,4))

In [ ]:
a =np.random.random(3)

print(a)
a.ndim
a.shape

In [ ]:
np.ones((2, 2), dtype=bool)
#np.ones((2, 2), dtype=int)

# Arange the numbers between x and y with an interval of z

In [ ]:
#import numpy as np
#the last number 10 is not printed
#np.arange(Start,End,Increment)
#End is exclusive
np.arange(1,10,1)



In [ ]:
#import numpy as np
#the last number 19 is not printed
np.arange(1,20,1)

# Another Example - Identity Matrix

In [ ]:
np.eye(3)

In [ ]:
arr_cond = np.arange(0,11)

In [ ]:
arr_cond>5  

# Arrange 'z' numbers between x and y

linspace-linear Space - linear equation

In [ ]:
#np.linspace(5-start,10-end,4-digits in between 5 and 10)
np.linspace(5,10,3)

#(10-5/3)


In [ ]:
np.linspace(5,10,5)
#1.25

In [ ]:
np.linspace(5,10,6)
#1

In [ ]:
np.linspace(0,10,6)
#2

Here the even space is .5

In [ ]:
#what is linspace???
#How to use it

np.linspace(5,10,10)
#.55

# Filling SAME number in an array of dimension x X y

In [ ]:
import numpy as np
np.full((2,3),5)

# Filling RANDOM number in an array of dimension x X y

In [ ]:

a = np.random.random((2,3))

#a =np.random
print(a)


# Inspecting the array: Checking the Shape of the array

Shape - Inspect the array, returns the rows and columns of array
Shape - can also be used for resizing the Array

In [ ]:
a = np.array([[2,3,4],[4,4,6]])

print(a)
print(a.shape)
print(a.ndim)
print('******')
b = np.array([2,3,4,5,6])
print(b)
print(b.shape)
print(b.ndim)


In [ ]:
s = np.array([[1,2,3,4],[2,3,4,6],[6,7,8,9]])
print(s.shape)


#  Resize the existing Array using SHAPE

In [ ]:
#shape = 2 rows x 3 cols
a = np.array([[2,3,4],[4,4,6]])
print(a)
print(a.shape)

print("*******")
#shape = 3 rows x 2 cols
a.shape = (3,2)
print(a)
print(a.shape)
print("*******")

a.shape = (2,3)
print(a)
print(a.shape)
print("*******")

b = np.array([[10,11,12],[13,14,15]])
b.shape = (3,2)
print(b)
print("*******")
b = np.array([[10,11,12],[13,14,15]])
b.shape = (1,6)
print(b)
#1 row and 6 coluums

In [ ]:
a = np.array([[2,3,4,4],[2,4,4,6]])
print(a)
print(a.ndim)
print(a.shape)
print('*******')
a.shape = (2,2) #Trick: x*y = Total number of elements in the array
print(a)
print(a.ndim)
print(a.shape)

# Reshape- copys the new shape to a new Numpy Array

In [ ]:
a = np.arange(24)
print(a)
print(a.ndim)
#reshape our array
print('*******')
b = a.reshape(12,2) #trick: Calculate the factors of 24: 1,2,3,4,6,12,24 
print(b)
print(b.ndim)

print(a)
print(a.shape)


###
#a = a.shape(12,2) #trick: Calculate the factors of 24: 1,2,3,4,6,12,24 
#a.shape =(12,2)
#print(a)
#print(a.ndim)



# Reshape

In [ ]:
# Python Program illustrating 
# numpy.reshape() method 

import numpy as geek 

array = geek.arange(8) 
print("Original array - 1 Dimension : \n", array) 

# shape array with 2 rows and 4 columns 
array = geek.arange(8).reshape(2, 4) 
print("\narray reshaped with 2 rows and 4 columns - 2 Dimensions: \n", array) 

# shape array with 2 rows and 4 columns 
array = geek.arange(8).reshape(4 ,2) 
print("\narray reshaped with 4 rows and 2 columns : - 2 Dimensions \n", array) 

# Constructs 3D array 
array = geek.arange(8).reshape(2, 2, 2) 
print("\nOriginal array reshaped to 3D : - 3 Dimensions \n", array) 


# Find the number of elements in an array

Returns the count of number of elements in an Array

In [ ]:
a = np.arange(24)

In [ ]:
print(a.size)

In [ ]:
d = np.array([[1,2,3,4],[4,5,6,4],[6,7,8,9]])
print(d.size)

# ndim

nadarray.ndim Dimensions of an Array-

In [ ]:
import numpy as np
a= np.arange(24)
#(24)
#(Columns)

print(a)
print(a.shape)
print(a.ndim)

c=a.reshape(8,3)
#(8,3)
#(Rows,Columns)

print(c)
print(c.ndim)

b=a.reshape(4,2,3)
#(4,2,3)
#(Layers,Rows,Columns)
print(b)
print(b.shape)
print(b.ndim)



# Find the datatype of the array

In [ ]:
a = np.arange(24, dtype=float)
print(a.size)
print(a.dtype)
a

In [ ]:
b=a.reshape(3,4,2)
b

# Numpy Array Mathematics: Addition

In [ ]:
import numpy as np
np.sum([10,20])

In [ ]:
#using a variable that is sum of a+b
a,b = 10,20
np.sum([a,b])

In [ ]:
#a=np.array([[1,2],[5,6]])
#print(a)
#print(a.sum())
#print(a.shape)
# np.sum([[1,2],[5,6]])
#b= np.sum([[1,2],[5,6]])
#print(b)
print('******')
b=np.sum([[1,2],[5,6]],axis = 0)
#axis 0 will add values in column
print(b)
#print(b.shape)

In [ ]:
a=np.array([[1,2],[5,6]])
print(a)
np.sum([[1,2],[5,6]],axis = 1)
#axis 1 will add values in rows

additions

In [ ]:
a= np.arange(5)
b= np.arange(5)
print (a)
print(b)

In [ ]:
a+b

# Numpy Array Mathematics: Subtraction

In [ ]:
np.subtract(10,20)

# All other numpy Mathematics Function

In [ ]:
np.multiply(2,3) #Multiplying two numbers

In [ ]:
np.divide(10,5) #Dividing two numbers

In [ ]:
a =np.array([2,4,6])
b =np.array([1,2,3])
np.multiply(a,b)

In [ ]:
#exp,sqrt,sin,cos,log
a =np.array([2,4,6])

print("Exponent : ",np.exp(a))
print("Square root : ", np.sqrt(a))
print("Sin : ", np.sin(a))
print("Cos : ", np.cos(a))
print("Log : ", np.log(a))

# List and  Numpy Array Comparison

In [ ]:
#List Comparision using Numpy
#Element-wise Comparison
a = [1,2,4]
b = [1,3,4]
#c = [1,2,4]
print(a)
print(b)
np.equal(a,b)

In [ ]:
#Numpy array comparision
#Array-wise Comparison
a = np.array([1,2,4])
b = np.array([1,4,4])
c = np.array([1,2,4])

print(type(c))
print(np.array_equal(a,c))
print(np.array_equal(a,b))

# Aggregate Function

In [ ]:
a = np.array([1,13,1])
b = np.array([1,12,1])
#c = np.array([1,2,4])
print("Sum: ",np.sum(a))
print("Minimum Value: ",np.min(a))
print("Mean: ",np.mean(a))
print("Median: ",np.median(a))
print("Coorelation Coefficient: ",np.corrcoef(a,b))
print("Standard Deviation: ",np.std(a))

# Concept of Broadcasting

In [ ]:
import numpy as np
a = np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b = np.array([0,1,2])
print (a)
print ('***')
print(b)
print ('***')
a+b

In [ ]:
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]

In [ ]:
import numpy as np
a = np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b = np.array([[0,1,2]])

a+b

In [ ]:
import numpy as np
a = np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b = np.array([[0,1,2]])
print("First Array: \n",a,'\n')
print("Second Array: \n",b,'\n')
print("First Array + Second Array: \n",a+b,'\n')

In [ ]:
a=np.arange(3).reshape((3,1))
print(a)

In [ ]:
b=np.arange(3)
print(b)

In [ ]:
a+b

In [ ]:
c= np.arange(3) 
print(c)

In [ ]:
d =5
print(5)

In [ ]:
c+d

# Difference in list and array

list does not behave like a numpy array

In [ ]:
a=[[0,0,0],[1,2,3],[4,5,6],[5,6,7]]

print(type(a))
b=[0,1,2]
print(type(b))
c=a+b
print(type(c))
print(c)

# Indexing and Slicing in Python

In [156]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [157]:
x.ndim

2

In [158]:
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [140]:
print(x.shape)

(3, 3)


In [141]:
x[0]

array([1, 2, 3])

# How slicing works 

#Array[Rows]<br>
#Array[Rows,Columns]<br>
#Array[RowStartIndex:RowEndIndex,ColumnStartIndex:ColumnEndIndex]<br>
#Array[RowStartIndex-Inclusive:RowEndIndex-Exclusive<br>
#,ColumnStartIndex-Inclusive:ColumnEndIndex-Exclusive]<br>
<br><br>***************<br>
#Array[RowStartIndex-Inclusive(empty-0):RowEndIndex-Exclusive<br>
#,ColumnStartIndex-Inclusive:ColumnEndIndex-Exclusive]<br>




Reverse the array
x[::-1]

In [142]:
print(x)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [143]:
x[0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

-1 is a simple place holder of the index

In [12]:
x[-1:,:]
#x[:,:]

array([[7, 8, 9]])

In [13]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
x[:1,1:]
#x[0:1,1:end]
#x[0:1,1:end]

array([[2, 3]])

In [15]:
x[:1,:]

array([[1, 2, 3]])

In [16]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
x[:3,:1]

array([[1],
       [4],
       [7]])

In [22]:
x[1:,1:]

array([[5, 6],
       [8, 9]])

In [23]:
x[-1:,-1:]

array([[9]])

In [166]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

Print the array in Reverse

In [ ]:
x[::-1]

Print the array in Reverse and the split

In [165]:
x[::-1][0:2]

array([[10, 11, 12],
       [ 7,  8,  9]])

In [148]:
x[:,-3:-1]
#x[:,0:-2]
#x[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [162]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [ ]:
#print(x[-1:,:-2])


In [ ]:
12
45
78

In [27]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
x[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
x[:2,1:]

array([[2, 3],
       [5, 6]])

In [30]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
x[1:,]



array([[4, 5, 6],
       [7, 8, 9]])

In [32]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
x[1:,1:]

array([[5, 6],
       [8, 9]])

In [34]:
x[3:,:1]

array([], shape=(0, 1), dtype=int32)

In [35]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Slices and Returns 1- D arrary

In [42]:
x[2]


array([7, 8, 9])

Slices and Returns 1- D arrary

In [43]:
x[2,:]

array([7, 8, 9])

Slices and Returns 2- D arrary

In [48]:
x[2:,:]

array([[7, 8, 9]])

In [49]:
x[:2,1:]

array([[2, 3],
       [5, 6]])

# List

In [50]:
a = ['m','o','n','t','y',' ','p','y','t','h','o','n']
a[2:9]

['n', 't', 'y', ' ', 'p', 'y', 't']

# Numpy Array

In [51]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[0]
a[:1]
print(a)
a[:1,1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3]])

In [52]:
a[:2,1:]

array([[2, 3],
       [5, 6]])

In [53]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

# Array Manipulation in Python

In [54]:
a = np.array([1,2,3])
b= np.array([4,5,6])
#concatenation of two arrays
print(a)
print(b)
print('***Concatenate**')
print(np.concatenate((a,b)))
a.ndim

[1 2 3]
[4 5 6]
***Concatenate**
[1 2 3 4 5 6]


1

# Stack - hstack, vstack

In [55]:
#Stack array row-wise: Horizontal 
print('a:')
print(a)
print('b:')
print(b)


a:
[1 2 3]
b:
[4 5 6]


In [56]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [57]:
#Stack array row-wise: Vertically
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
#Combining Column-wise
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
0,1,2,3,
4,5,6,7

In [61]:
c = np.arange(8).reshape(2,4)
print(c)

[[0 1 2 3]
 [4 5 6 7]]


In [62]:
d = np.arange(8).reshape(2,4)
print(c)

[[0 1 2 3]
 [4 5 6 7]]


In [63]:
np.hstack((c,d))

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7]])

In [64]:
np.vstack((c,d))

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

# Splitting Array

In [68]:
#split, a single parameter is used for splitting
c = np.arange(8)
print(c)
d = np.split(c,2)
print(d)
##there elements should match the values we are trying to split


[0 1 2 3 4 5 6 7]
[array([0, 1, 2, 3]), array([4, 5, 6, 7])]


In [69]:
#split
c = np.arange(8).reshape(2,4)
print(c)
d = np.split(c,2)
print(d)
##there elements should match the values we are trying to split


[[0 1 2 3]
 [4 5 6 7]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]])]


In [70]:
#when parameter is passed as a list,the list of data is used a index for splitting
c = np.arange(8)
print(c)
d = np.split(c,[2,5])
print(d)
#there elements should match the values we are trying to split



[0 1 2 3 4 5 6 7]
[array([0, 1]), array([2, 3, 4]), array([5, 6, 7])]


In [71]:
c = np.arange(8)
print(c)
d = np.split(c,[2,3,9])
print(d)
#there elements should match the values we are trying to split



[0 1 2 3 4 5 6 7]
[array([0, 1]), array([2]), array([3, 4, 5, 6, 7]), array([], dtype=int32)]


# Hsplit

In [83]:
x = np.arange(16).reshape(4,4)

print(x,"\n\n")
#print(np.hsplit(x,2))

print("***1,3***")
#hsplit using Index, you pass a list of index
print("\n\n", np.hsplit(x,[1,3]))
print("***1,4***")
#hsplit using Index, you pass a list of index
print("\n\n", np.hsplit(x,[1,4]))
print("***2,3***")
#hsplit using Index, you pass a list of index
print("\n\n", np.hsplit(x,[2,3]))
print("***2,4***")
print("\n\n", np.hsplit(x,[2,4]))
#print("\n\n", np.hsplit(x,np.array([2,4])))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


***1,3***


 [array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
***1,4***


 [array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]]), array([], shape=(4, 0), dtype=int32)]
***2,3***


 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
***2,4***


 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


In [ ]:
#np.arange(16)

In [ ]:
x

In [84]:
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
x

In [85]:
print("\n\n", np.vsplit(x,[2,4]))



 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([], shape=(0, 4), dtype=int32)]


# Ravel() and Flatten()

Ravel() - method is used for Flattening of Arrays.
Flattening of arrays are used when you have to pass it to a deeplearning algorithm
<br>
Flatten also takes parameters for row=c, column=f


# Flatten Vs Ravel:



The flatten method always returns a copy. Whereas the ravel method returns a view of the original array whenever possible. When you print the output this will not be visible, but if you modify the array returned by ravel, it may modify the entries in the original array.

import numpy as np
a = np.arange(12).reshape(3,4)

In [100]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
print('***ravel***')
#-ravel flattens orginal array
#print(a.ravel())
#print(a.ravel())
#a
#print('***flatten***')
#'C' means to flatten in row-major (C-style) order.
#'F' means to flatten in column-major 
#a.flatten()
#print(a.flatten())

#a.flatten(order='C')
a.flatten(order='F')

***ravel***


array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [96]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Create a multi dimensional array

# (-1 in reshape)

When you use -1 in the reshape, numpy will automatically determine what size/lenght a particular dimension should be . 

In [125]:
a = np.arange(1,13).reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [129]:
a1 = np.arange(1,13).reshape(6,-1)

In [130]:
print(a1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [116]:
a1 = np.arange(1,13).reshape(-1,4)

In [117]:
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [118]:
a1 = np.arange(1,13).reshape(2,-1)

In [119]:
print(a1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


create a multidimensional arrayrs from 2 d arrays

In [120]:
a1 = np.arange(1,13).reshape(3,-1)
a2 = np.arange(1,13).reshape(3,-1)
print(a1)
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [121]:
a3_0= np.stack((a1,a2))

In [122]:
print(a3_0)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [ ]:
a3_0d= np.stack((a1,a2),axis=0)
print(a3_0d)

In [ ]:
a3_1= np.stack((a1,a2),axis=1)

In [ ]:
print(a3_1)

# Advantages of Numpy Over a List

In [ ]:
dir(np)

# Numpy vs List: Memory size

In [170]:
#Numpy vs List: Memory size
import numpy as np
import sys

#define a list- values from 0 to 999
l = range(1000)
print(l)

print("Size of one element in the list: ",sys.getsizeof(1))
print("lenght of the list: ",len(l))

print("Size of a 1: ",sys.getsizeof(1))
print("Total Size of the list: ",sys.getsizeof(1)*len(l))
print("Size of a element 0 in the list: ",sys.getsizeof(0)*len(l))



print("*********numpy size*******")

#define a numpy array-values from 0 to 999
a = np.arange(1000)
print("Size of each element in the np array: ",a.itemsize)
print("Size of an np array: ",a.size*a.itemsize)

#print("***")
#print("Size of a np: ",sys.getsizeof(a))


range(0, 1000)
Size of one element in the list:  28
lenght of the list:  1000
Size of a 1:  28
Total Size of the list:  28000
Size of a element 0 in the list:  24000
*********numpy size*******
Size of each element in the np array:  4
Size of an np array:  4000


# Numpy vs List: Speed of Calculations

In [172]:

import time

def using_List():
    st1 = time.time()#Starting/Initial Time
    X = range(100000)
    Y = range(100000)
    z = [X[i]+Y[i] for i in range(len(X))]
    return time.time()-st1

def using_Numpy():
    npst1 = time.time()#Starting/Initial Time
    a = np.arange(100000)
    b = np.arange(100000)
    c =a+b #more convient than a list
    return time.time()-npst1



list_time = using_List()
numpy_time = using_Numpy()

print(list_time,numpy_time)

#this line will print an error because Nump somestime can be zero. Run very fast
#print("In this example Numpy is "+str(list_time/numpy_time)+" times faster than a list")

0.08875727653503418 0.0


# COPY()

Numpy is Mutable, if you use =, if you use copy method of NP, it will create separate instance

In [ ]:
a = np.arange(5)

In [ ]:
print(a)

In [ ]:
b=a

In [ ]:
print(b)

In [ ]:
b[0]=100

In [ ]:
print(a)

In [ ]:
b=a.copy()

In [ ]:
print(b)

In [ ]:
b[0]=10

In [ ]:
print(a)

In [ ]:
print(b)

# Numpy Loading Examples

# Numpy Data Storage Examples - 2d and 3d

Numpy array for 2 dimensions using .csv files

In [ ]:
import csv
with open('winequality-red.csv', 'r') as f:
    wines = list(csv.reader(f, delimiter=';'))

 If we pass in a list of lists, it will automatically create a NumPy array with the same number of rows and columns.<br>
 Here the first row is text and it will be considered as a string

In [ ]:
print(wines[:3])

In [ ]:
type(wines)

Exclude the header row with list slicing. so we can skip the header

In [ ]:
import csv
with open("winequality-red.csv", 'r') as f:
    wines = list(csv.reader(f, delimiter=";"))
import numpy as np
wines = np.array(wines[1:], dtype=np.float)

In [ ]:
print(wines.shape)

In [ ]:
type(wines)

In [ ]:
print(wines[:3])

In [ ]:
wines

In [ ]:
third_wine = wines[:,:]

In [ ]:
third_wine 

# Numpy array for 3 dimensions using image processing 

In [ ]:
# check Pillow version number
#Python Image Library
import PIL
print('Pillow Version:', PIL.__version__)

In [ ]:
# load and show an image with Pillow
from PIL import Image
# Open the image form working directory


#image = Image.open('applelogo.png')
#Colorful flower
image = Image.open('image1.jpg')


# summarize some details about the image
print(image.format)
print(image.size)
print(image.mode)
# show the image
image.show()

# Load image data into Numpy

In [ ]:
from PIL import Image
#from numpy import asarray
from numpy import array

# load the image
image = Image.open('applelogo.png')
#image = Image.open('image1.jpg')
# convert image to numpy array - using asarray or array
#data = asarray(image)
#data = asarray(image)
data = array(image)


print(type(data))
# summarize shape
print(data.shape)
print(data.ndim)
print(data)

In [ ]:
image

In [ ]:
print(type(image))
# summarize shape


print(image)

# More Examples    

In [ ]:
import numpy as np
a1 = np.arange(1, 13)  # numbers 1 to 12
print(a1.shape)
print(a1)


# Reshape with reshape() method

In [ ]:
a1_2d = a1.reshape(3, 4)  # 3_4
print(a1_2d.shape)
print(a1_2d)

# Automatic Reshape the Size use -1

numpy to automatically determine what size/length a particular dimension should be, specify the dimension as -1 for that dimension.

In [ ]:
a1.reshape(3, 4)
a1.reshape(-1, 4)  # same as above: a1.reshape(3, 4)


In [ ]:
a1.reshape(3, 4)
a1.reshape(3, -1)  # same as above: a1.reshape(3, 4)


In [ ]:
a1.reshape(2, 6)
a1.reshape(2, -1)  # same as above: a1.reshape(2, 6)

# Reshape along different dimensions

In [ ]:
#a1.reshape(3, 4) # reshapes or ‘fills in’ row by row
a1.reshape(3, 4, order='C') # same results as above
#reshapes or ‘fills in’ row by row, left to right

 reshape along the 1st dimension (column) by changing order to 'F'. For those familiar with MATLAB, MATLAB uses this order.

In [ ]:
a1.reshape(3, 4, order='F')  # reshapes column by column
#reshapes or ‘fills in’ row by row, left to right
#column by column

What’s the dimension/shape of array a1?

In [ ]:
print(a1)  # what's the shape?

print(a1.shape)


In [ ]:

a1_1_by_12 = a1.reshape(1, -1)  # reshape to 1_12
print(a1_1_by_12)  # note the double square brackets!


In [ ]:

print(a1_1_by_12.shape)  # 1_12 array


# Flatten/ravel to 1D arrays with ravel()

In [ ]:
print(a1_2d)  # 3_4
#flatten 2-d array along th column
print(a1_2d.ravel())  # ravel by row (default order='C')




In [ ]:
print(a1_2d.ravel(order='F'))  # ravel by column

# Concatenate/stack arrays with np.stack() and np.hstack()

In [ ]:
#2 , 1-d arrays

In [ ]:
a1 = np.arange(1, 13)
print(a1)

a2 = np.arange(13, 25)
print(a2)


In [ ]:
#by Default order 0 axis , row wise,left to right
stack0 = np.stack((a1, a1, a2, a2))  # default stack along 0th axis
print(stack0.shape)

print(stack0)


In [ ]:
stack1 = np.stack((a1, a1, a2, a2), axis=1)
print(stack1.shape)

print(stack1)


# Concatenate as a long 1D array with np.hstack() (stack horizontally)

In [ ]:
stack_long = np.hstack((a1, a2))
print(stack_long.shape)

print(stack_long)


# Create multi-dimensional array (3D)

In [ ]:
a1 = np.arange(1, 13).reshape(3, -1)  # 3_4
a2 = np.arange(13, 25).reshape(3, -1)  # 3_4
print(a1)

print(a2)


# Create a 3D array by stacking the arrays along different axes/dimensions

3d Arrary from 2d arrays

In [ ]:
a3_0 = np.stack((a1, a2))  # default axis=0 (dimension 0)
a3_1 = np.stack((a1, a2), axis=1)  # along dimension 1
a3_2 = np.stack((a1, a2), axis=2)  # along dimension 2
print(a3_0.shape)

print(a3_1.shape)
print(a3_2.shape)


In [ ]:
print(a3_0)

print(a3_1)
print(a3_2)


# How can we retrieve our a1 array from these 3D arrays?

if we want to retrieve the original two arrays from these 3D arrays, we’ll have to subset along the correct dimension/axis.

In [ ]:
print(a1)  # check what's a1

# solutions

a3_0[0, :, :]
a3_0[0]  # same as above
a3_1[:, 0, :]
a3_2[:, :, 0]

# Flatten multidimensional arrays

multi-dimensional arrays with ravel(). Below, we ravel row by row (default order='C') to 1D array.

In [ ]:
print(a3_0)

print(a3_0.ravel())


In [ ]:
print(a3_0.ravel(order='F'))


# Reshape multidimensional arrays

In [ ]:
#reshape row by row (default order=C) to 2D array
print(a3_0)  # 2_3_4
print(a3_0.reshape(4, -1))  # reshape to 4_6 (row by row)
print(a3_0.reshape(4, -1, order='F'))  # reshape (column by column)
print(a3_0.reshape(4, 2, 3))  # reshape to 4_2_3 (row by row)
