In [2]:
import numpy as np
import pandas as pd

In [3]:
golf_df1 = pd.DataFrame()

# Predict the Golf Play using 1 Variable - Outlook

In [4]:
# Assigning features and label variables
outlook=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [5]:
outlook

['Sunny',
 'Sunny',
 'Overcast',
 'Rainy',
 'Rainy',
 'Rainy',
 'Overcast',
 'Sunny',
 'Sunny',
 'Rainy',
 'Sunny',
 'Overcast',
 'Overcast',
 'Rainy']

In [7]:
# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
outlook_encoded=le.fit_transform(outlook)
print (outlook_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [8]:
# Converting string labels into numbers
play_encoded=le.fit_transform(play)

print ("Play:",play_encoded)

Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [9]:
print ('outlook:',outlook_encoded)

print ("Play:",play_encoded)

outlook: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [16]:
#-1 - Dynamically assigned - Rows -14
#1 Column
outlook_encoded3=outlook_encoded.reshape(2, -1)
outlook_encoded3

array([[2, 2, 0, 1, 1, 1, 0],
       [2, 2, 1, 2, 0, 0, 1]], dtype=int64)

In [14]:
#-1 to dynamical set the number of rows for the 2 dimensions numpy array
outlook_encoded2=outlook_encoded.reshape(-1, 1)

In [15]:
print(outlook_encoded2)

[[2]
 [2]
 [0]
 [1]
 [1]
 [1]
 [0]
 [2]
 [2]
 [1]
 [2]
 [0]
 [0]
 [1]]


In [19]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(outlook_encoded2,play_encoded)

#Predict Output
predicted= model.predict([[2]]) # 2:Outlook:Sunny,# 1:Outlook:rainy
#0:Play - No
print ("Predicted Value:", predicted)

Predicted Value: [0]


In [20]:
if predicted==[1]:
    print("Play:","YES")
else:
    print("Play:","NO")

Play: NO


In [21]:
#Predict Output
predicted= model.predict([[0]]) # 0:Outlook:Overcast, 
print ("Predicted Value:", predicted)
#1:Play - Yes

Predicted Value: [1]


In [22]:
if predicted==[1]:
    print("Play:","YES")
else:
    print("Play:","NO")

Play: YES


# Predict the Golf Play using multiple Variable - Outlook,Temp

In [25]:
# Assigning features and label variables
outlook=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [26]:
# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
outlook_encoded_m=le.fit_transform(outlook)
print (outlook_encoded_m)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [28]:
temp_encoded_m=le.fit_transform(temp)
play_encoded_m=le.fit_transform(play)
print ('outlook:',outlook_encoded_m)
print ("Temp   :",temp_encoded_m)
print ("Play   :",play_encoded_m)

outlook: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp   : [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play   : [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [34]:
type(outlook_encoded_m)

numpy.ndarray

In [37]:
list(zip(outlook_encoded_m,temp_encoded_m))


[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [29]:
#Combinig weather and temp into single list
features=list(zip(outlook_encoded_m,temp_encoded_m))

#print(tuple(features))
print(features)

[(2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2)]


In [31]:
#Create a Gaussian Classifier
model_m = GaussianNB()

# Train the model using the training sets
model_m.fit(features,play_encoded)

#Predict Output
predicted_m= model_m.predict([[0,2]]) # 0:Outlook:Overcast, 2:Temp:Mild 
#1:Play - Yes
print ("Predicted Value:", predicted_m)

Predicted Value: [1]


In [32]:
#Predict Output
predicted_m= model_m.predict([[1,2]])  # 1:Outlook:Rain, 2:Temp:Mild 
print ("Predicted Value:", predicted_m)

Predicted Value: [1]
